5. Grouping (MOST IMPORTANT)
Questions:
Count permits per zipcode
Average street number per neighborhood
Which permit type occurs most?
Count permits by supervisor district
Group by permit type + zipcode

6. Aggregation
Questions:
Max street number
Mean construction type
Count unique neighborhoods
Multiple aggregations together

In [1]:
import numpy as np 
import pandas as pd

In [27]:
df = pd.read_csv("Practice.csv")
df.dropna(how="all")
df

C:\Users\Vishal Kumar\AppData\Local\Temp\ipykernel_22044\3354671636.py:1: DtypeWarning: Columns (0: Voluntary Soft-Story Retrofit, 1: TIDF Compliance) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Practice.csv")

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,2.02E+11,4,sign - erect,05-06-2015,326,23,140,NaN,Ellis,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1.380000e+12
1,2.02E+11,4,sign - erect,04/19/2016,306,7,440,NaN,Geary,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)",1.420000e+12
2,2.02E+11,3,additions alterations or repairs,05/27/2016,595,203,1647,NaN,Pacific,Av,...,1.0,constr type 1,1.0,constr type 1,NaN,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)",1.420000e+12
3,2.02E+11,8,otc alterations permit,11-07-2016,156,11,1230,NaN,Pacific,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)",1.440000e+12
4,2.02E+11,6,demolitions,11/28/2016,342,1,950,NaN,Market,St,...,3.0,constr type 3,NaN,NaN,NaN,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",1.450000e+11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198895,M862628,8,otc alterations permit,12-05-2017,113,017A,1228,NaN,Montgomery,St,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.490000e+12
198896,2.02E+11,8,otc alterations permit,12-05-2017,271,14,580,NaN,Bush,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,NaN,NaN,NaN,NaN,1.490000e+12
198897,M863507,8,otc alterations permit,12-06-2017,4318,19,1568,NaN,Indiana,St,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.490000e+12
198898,M863747,8,otc alterations permit,12-06-2017,298,29,795,NaN,Sutter,St,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.490000e+12
198899,M864287,8,otc alterations permit,12-07-2017,160,6,838,NaN,Pacific,Av,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.490000e+12

In [23]:
df["Zipcode"].unique()

array([94102., 94109., 94107., 94122., 94124., 94117., 94114., 94131.,
       94115., 94108., 94104., 94123., 94110., 94133., 94121., 94105.,
       94103., 94118., 94132., 94112., 94134., 94116., 94127., 94158.,
       94130., 94111.,    nan, 94129.])

In [24]:
#Count permits per zipcode
df.groupby("Zipcode")["Permit Number"].count()

Zipcode
94102.0     7164
94103.0    10986
94104.0     4229
94105.0     8628
94107.0     7706
94108.0     5320
94109.0    11348
94110.0    17837
94111.0     5385
94112.0     7897
94114.0    13404
94115.0    10095
94116.0     6421
94117.0    11780
94118.0     9812
94121.0     7773
94122.0     8886
94123.0     9515
94124.0     5265
94127.0     4993
94129.0       23
94130.0       81
94131.0     7664
94132.0     3507
94133.0     7424
94134.0     2983
94158.0     1058
Name: Permit Number, dtype: int64

In [25]:
#Average street number per neighborhood
df.groupby("Neighborhoods - Analysis Boundaries")["Street Number"].mean()

Neighborhoods - Analysis Boundaries
Bayview Hunters Point             1234.497619
Bernal Heights                     736.326521
Castro/Upper Market               1323.861264
Chinatown                          709.417795
Excelsior                          727.561198
Financial District/South Beach     277.059223
Glen Park                          571.782328
Golden Gate Park                   638.843750
Haight Ashbury                     774.354088
Hayes Valley                       549.874112
Inner Richmond                     820.554060
Inner Sunset                      1107.696157
Japantown                         1752.345714
Lakeshore                         1016.367737
Lincoln Park                       298.693878
Lone Mountain/USF                 1257.594104
Marina                            2225.768923
McLaren Park                      1055.304348
Mission                           1532.695457
Mission Bay                        530.254482
Nob Hill                          1083.822267
Noe Valley                        1636.967364
North Beach                        839.397385
Oceanview/Merced/Ingleside         441.873022
Outer Mission                     1006.617306
Outer Richmond                    1458.982302
Pacific Heights                   2317.866831
Portola                            917.629449
Potrero Hill                       992.736082
Presidio                          1264.627451
Presidio Heights                  2006.521058
Russian Hill                      1485.337034
Seacliff                           657.978831
South of Market                    696.683571
Sunset/Parkside                   1967.363378
Tenderloin                         520.029061
Treasure Island                    638.864198
Twin Peaks                         543.754994
Visitacion Valley                  460.685556
West of Twin Peaks                 582.683946
Western Addition                  1293.483579
Name: Street Number, dtype: float64

In [26]:
#Which permit type occurs most?
df["Permit Type"].idxmax()

3

In [29]:
#Count permits by supervisor district

df.groupby("Supervisor District")["Permit Number"].count()

Supervisor District
1.0     13038
2.0     25483
3.0     28649
4.0      9592
5.0     19045
6.0     24797
7.0     14365
8.0     26760
9.0     16362
10.0    12152
11.0     6940
Name: Permit Number, dtype: int64

In [52]:
#Group by permit type + zipcode

df.groupby(["Zipcode" , "Permit Type"]).count()

                     Permit Number  Permit Type Definition  \
Zipcode Permit Type
94102.0 1                       40                      40
        2                        6                       6
        3                      604                     604
        4                      255                     255
        5                        2                       2
...                            ...                     ...
94158.0 4                       59                      59
        5                        4                       4
        6                        1                       1
        7                        8                       8
        8                      854                     854

                     Permit Creation Date  Block  Lot  Street Number  \
Zipcode Permit Type
94102.0 1                              40     40   40             40
        2                               6      6    6              6
        3                             604    604  604            604
        4                             255    255  255            255
        5                               2      2    2              2
...                                   ...    ...  ...            ...
94158.0 4                              59     59   59             59
        5                               4      4    4              4
        6                               1      1    1              1
        7                               8      8    8              8
        8                             854    854  854            854

                     Street Number Suffix  Street Name  Street Suffix  Unit  \
Zipcode Permit Type
94102.0 1                               0           40             40     4
        2                               0            6              6     0
        3                               4          604            604    73
        4                               0          255            255    27
        5                               0            2              2     0
...                                   ...          ...            ...   ...
94158.0 4                               0           59             59    15
        5                               0            4              4     2
        6                               0            1              0     0
        7                               0            8              7     3
        8                               0          854            805   200

                     ...  TIDF Compliance  Existing Construction Type  \
Zipcode Permit Type  ...
94102.0 1            ...                0                           0
        2            ...                0                           0
        3            ...                0                         537
        4            ...                0                         252
        5            ...                0                           0
...                  ...              ...                         ...
94158.0 4            ...                0                          59
        5            ...                0                           0
        6            ...                0                           1
        7            ...                0                           0
        8            ...                0                         576

                     Existing Construction Type Description  \
Zipcode Permit Type
94102.0 1                                                 0
        2                                                 0
        3                                               537
        4                                               252
        5                                                 0
...                                                     ...
94158.0 4                                                59
        5                                                 0
        6                                                 1
        7                                                 0
        8                                               576

                     Proposed Construction Type  \
Zipcode Permit Type
94102.0 1                                    40
        2                                     5
        3                                   589
        4                                     0
        5                                     0
...                                         ...
94158.0 4                                     0
        5                                     0
        6                                     0
        7                                     0
        8                                   635

                     Proposed Construction Type Description  Site Permit  \
Zipcode Permit Type
94102.0 1                                                40           39
        2                                                 5            5
        3                                               589           53
        4                                                 0            0
        5                                                 0            0
...                                                     ...          ...
94158.0 4                                                 0            0
        5                                                 0            0
        6                                                 0            0
        7                                                 0            0
        8                                               635            0

                     Supervisor District  Neighborhoods - Analysis Boundaries  \
Zipcode Permit Type
94102.0 1                             40                                   40
        2                              6                                    6
        3                            604                                  604
        4                            255                                  255
        5                              2                                    2
...                                  ...                                  ...
94158.0 4                             59                                   59
        5                              4                                    4
        6                              1                                    1
        7                              8                                    8
        8                            854                                  854

                     Location  Record ID
Zipcode Permit Type
94102.0 1                  40         40
        2                   6          6
        3                 604        604
        4                 255        255
        5                   2          2
...                       ...        ...
94158.0 4                  59         59
        5                   4          4
        6                   1          1
        7                   8          8
        8                 854        854

[196 rows x 41 columns]